# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "AudioExample")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    ios_set_version(
      version: ENV["VERSION_NAME"]
    )

    ios_set_build_number(
      build_number: ENV["VERSION_CODE"]
    )

    gym(
      scheme: "AudioExample"
    ) # Build your app - more options available

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_path: ENV["FIREBASE_CLI_PATH"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      testers: ENV["FIREBASE_APP_DISTRIBUTION_TESTERS"],
      groups: ENV["FIREBASE_APP_DISTRIBUTION_GROUPS"]
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
