# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
    )

    android_set_version_code(
      version_code: ENV["VERSION_CODE"],
    )

    gradle(task: "assembleRelease")
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_path: ENV["FIREBASE_CLI_PATH"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      testers: ENV["FIREBASE_APP_DISTRIBUTION_TESTERS"],
      groups: ENV["FIREBASE_APP_DISTRIBUTION_GROUPS"],
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
